In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("emails.csv")

In [6]:
df.tail(15)

text  spam
5713  Subject: promotion  vince , i want to congratu...     0
5714  Subject: re : petronas benchmarking visit  fyi...     0
5715  Subject: request submitted : access request fo...     0
5716  Subject: * special notification * aurora versi...     0
5717  Subject: fwd : update  return - path :  receiv...     0
5718  Subject: altos na gas model  kim , i know you ...     0
5719  Subject: power market research  i came across ...     0
5720  Subject: re : visit to houston  fyi  - - - - -...     0
5721  Subject: ees risk management presentations for...     0
5722  Subject: re : vacation  vince :  i just found ...     0
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.text,df.spam)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train_count,y_train)

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [23]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [24]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.99231843575419

In [25]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [26]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [27]:

clf.predict(emails)

array([0, 1], dtype=int64)

In [28]:
clf.score(X_test,y_test)

0.99231843575419